name: deploy

on:
   push:
      branches:
         - prod

jobs:
   firebase:
      runs-on: ubuntu-18.04
      steps:
         - uses: actions/checkout@v2
         - name: Setup NodeJS
           uses: actions/setup-node@v1
           with:
              node-version: 13.x
         - name: Install Firebase Tools
           run: |
              npm i -g firebase-tools
         - name: Install Dependencies
           run: yarn
         - name: Deploying App
           run: firebase deploy --project clashamigos --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
